;;;; Reload N-word / messaging expander, then OBJC-SUPPORT + NSString smoke.
(in-package :ccl)
(setq *warn-if-redefine-kernel* nil)
;; Expander (skip :variadic for objc_msgSend*)
(let* ((src (merge-pathnames "lib/foreign-types.lisp" (ccl-directory)))
       (wanted '(objc-messaging-entry-name-p %external-call-expander))
       (forms ()))
  (with-open-file (s src)
    (loop for f = (read s nil s)
          until (eq f s)
          when (and (consp f) (eq (car f) 'defun) (member (cadr f) wanted))
          do (push f forms)))
  (dolist (f (nreverse forms)) (eval f))
  (format t "~&expander ok (~d)~%" (length forms)))
;; aapcs64-ff-call (N-word struct args)
(let* ((src (merge-pathnames "compiler/ARM64/arm642.lisp" (ccl-directory)))
       (helpers ())
       (ffcall nil))
  (with-open-file (s src)
    (loop for f = (read s nil s)
          until (eq f s)
          do (cond ((and (consp f)
                         (member (car f) '(defun defarm642))
                         (member (cadr f)
                                 '(arm642-aapcs64-stack-arg-bytes
                                   arm642-align-up
                                   arm642-aapcs64-ff-call)))
                    (if (eq (cadr f) 'arm642-aapcs64-ff-call)
                      (setq ffcall f)
                      (push f helpers))))))
  (dolist (h (nreverse helpers)) (eval h))
  (eval ffcall)
  (format t "~&aapcs64 ok~%"))
;; interpreted %ff-call N-word packing (optional; varargs uses %do-ff-call)
(let* ((src (merge-pathnames "level-0/ARM64/arm64-def.lisp" (ccl-directory)))
       (ff nil))
  (with-open-file (s src)
    (loop for f = (read s nil s)
          until (eq f s)
          when (and (consp f) (eq (car f) 'defun) (eq (cadr f) '%ff-call))
          do (setq ff f)))
  (when ff (eval ff) (format t "~&%ff-call ok~%")))
(require "OBJC-SUPPORT")
(format t "~&objc-support loaded~%")
(let* ((s (%make-nsstring "darwinarm64"))
       (len (#/length s)))
  (format t "~&s=~s len=~s~%" s len)
  (unless (and (integerp len) (eql len 11))
    (error "NSString length => ~s" len))
  (format t "~&DARWIN-OBJC-BRIDGE-SMOKE-OK len=~d~%" len))
;; Struct-arg path: NSRange is 2× NSUInteger (not HFA).
(let* ((s (%make-nsstring "abcdef"))
       (r (ns:make-ns-range 1 3))
       (sub (#/substringWithRange: s r)))
  (format t "~&substring=~s~%" (%get-cstring (#/UTF8String sub))))
(quit 0)
