;;;; Standalone-like Hemlock BOGUS probe (load via --eval, not stdin forms).
(in-package :ccl)
(require "COCOA")
(timed-wait-on-semaphore gui::*cocoa-ide-finished-launching* 60)
(load (merge-pathnames "tools/ide-modeline-stream-concat-patch.lisp" (ccl-directory)))
(load (merge-pathnames "tools/ide-listener-persist-patch.lisp" (ccl-directory)))
(setq gui::*standalone-cocoa-ide* t)
(setq gui::*first-listener* t)
(defparameter *out* "/tmp/ide-standalone-bogus.out")
(ignore-errors (delete-file *out*))
(defun lg (fmt &rest a)
  (with-open-file (s *out* :direction :output :if-exists :append :if-does-not-exist :create)
    (apply #'format s fmt a) (terpri s) (force-output s))
  (apply #'format t fmt a) (terpri) (force-output))
(setq *debugger-hook*
      (lambda (c h)
        (declare (ignore h))
        (lg "DBG ~a" c)
        (ignore-errors
          (with-open-file (s *out* :direction :output :if-exists :append)
            (let ((*standard-output* s) (*debug-io* s))
              (print-call-history :count 80 :detailed-p t))))
        (#_exit 99)))
(lg "create")
(gui::queue-for-gui
 (lambda ()
   (#/setActivationPolicy: *nsapp* 0)
   (#/newListener: (#/delegate *nsapp*) (%null-ptr))))
(#_usleep 1000000)
(lg "alive ~s"
    (mapcar #'process-name
            (remove-if-not (lambda (p) (typep p 'gui::cocoa-listener-process))
                           (all-processes))))
(gui::execute-in-gui
 (lambda ()
   (let ((frame nil) (hv nil))
     (dotimes (i (#/count (#/orderedWindows *nsapp*)))
       (let* ((w (#/objectAtIndex: (#/orderedWindows *nsapp*) i))
              (wc (#/windowController w)))
         (when (typep wc 'gui::hemlock-listener-window-controller)
           (setq frame w hv (gui::hemlock-view w)))))
     (lg "hv=~s" hv)
     (when hv
       (let ((hi::*current-buffer* (hi::hemlock-view-buffer hv)))
         (hi::update-modeline-fields hi::*current-buffer*)
         (lg "modeline ok"))
       (hi::handle-hemlock-event hv #\y)
       (lg "insert ok")
       (#/display frame)
       (lg "display ok")
       (let* ((pane (hi::hemlock-view-pane hv))
              (ml (ignore-errors (slot-value pane 'gui::mode-line))))
         (lg "mode-line=~s" ml)
         (when ml
           (#/setNeedsDisplay: ml t)
           (#/display ml)
           (lg "mode-line display ok")))))))
(#_usleep 500000)
(lg "IDE-STANDALONE-BOGUS-OK")
(format t "~&IDE-STANDALONE-BOGUS-OK~%")
(force-output)
(quit 0)
