(in-package :ccl)
(require "COCOA")
(timed-wait-on-semaphore gui::*cocoa-ide-finished-launching* 60)
(gui::queue-for-gui (lambda () (#/newListener: (#/delegate *nsapp*) (%null-ptr))))
(#_usleep 1000000)
(with-open-file (out "/tmp/ide-bounds-real.out" :direction :output :if-exists :supersede)
  (flet ((lg (fmt &rest a)
           (apply #'format out fmt a) (terpri out) (force-output out)
           (apply #'format t fmt a) (terpri) (force-output)))
    (gui::execute-in-gui
     (lambda ()
       (dotimes (i (#/count (#/orderedWindows *nsapp*)))
         (let* ((w (#/objectAtIndex: (#/orderedWindows *nsapp*) i))
                (wc (#/windowController w)))
           (when (typep wc 'gui::hemlock-listener-window-controller)
             (let* ((hv (gui::hemlock-view w))
                    (pane (hi::hemlock-view-pane hv))
                    (ml (ignore-errors (gui::text-pane-mode-line pane))))
               (lg "ml=~s" ml)
               (when ml
                 (let ((bounds (#/bounds ml)))
                   (lg "bounds=~s type=~s" bounds (type-of bounds))
                   (handler-case
                       (let ((rw (ns:ns-rect-width bounds))
                             (rh (ns:ns-rect-height bounds)))
                         (lg "rw=~s (~s) rh=~s (~s)" rw (type-of rw) rh (type-of rh))
                         (lg "float-w=~s" (float rw 1.0d0)))
                     (error (c) (lg "BOUNDS-ERR ~a" c)))))))))))
  (format out "IDE-BOUNDS-REAL-OK~%")
  (force-output out))
(format t "~&IDE-BOUNDS-REAL-OK~%")
(force-output)
(quit 0)
