;;;; Verify File → New Listener stays alive (*batch-flag* nil in process).
;;;; Separate top-level forms: create can process-reset the batch tty mid-form.
;;;;   ./tools/run-darwin-ide-smoke.sh 45 tools/ide-new-listener-persist.lisp \\
;;;;     IDE-NEW-LISTENER-PERSIST-OK
(in-package :ccl)
(require "COCOA")
(timed-wait-on-semaphore gui::*cocoa-ide-finished-launching* 60)
(load (merge-pathnames "tools/ide-modeline-stream-concat-patch.lisp" (ccl-directory)))
(load (merge-pathnames "tools/ide-listener-persist-patch.lisp" (ccl-directory)))
(defun %snap ()
  (mapcar (lambda (p)
            (list (process-name p)
                  (process-whostate p)
                  (process-exhausted-p p)
                  (ignore-errors (symbol-value-in-process '*batch-flag* p))))
          (remove-if-not (lambda (p) (typep p 'gui::cocoa-listener-process))
                         (all-processes))))
(format t "~&before ~s gui-batch=~s~%" (%snap) (find-symbol "*BATCH-FLAG*" :gui))
(force-output)
(gui::queue-for-gui
 (lambda ()
   (#/setActivationPolicy: *nsapp* 0)
   (#/newListener: (#/delegate *nsapp*) (%null-ptr))))
(#_usleep 500000)
(format t "~&t0 ~s~%" (%snap))
(force-output)
(#_usleep 500000)
(format t "~&t1 ~s~%" (%snap))
(force-output)
(let ((s (%snap)))
  (format t "~&final ~s~%" s)
  (force-output)
  (if (find-if (lambda (p) (and (not (third p)) (null (fourth p)))) s)
    (progn (format t "~&IDE-NEW-LISTENER-PERSIST-OK~%") (force-output) (quit 0))
    (progn (format t "~&IDE-NEW-LISTENER-PERSIST-FAIL~%") (force-output) (quit 1))))
